config/routes.rb
MHacksPillDeliveryQuad::Application.routes.draw do
  resources :requested_medicines

  resources :requests

  resources :histories

  resources :copters

  resources :destinations

  resources :medicines

  resources :users

  resources :hospitals

  root :to => 'hospitals#index'

  match '/process_sms' => 'receive_messages#process_sms', via: [:post]
  post '/send_sms' => 'receive_messages#butts', as: 'send_sms'
  post '/send_group_sms' => 'receive_messages#groupMessage'

  

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  belongs_to :hospital
  has_many :requested_medicines
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medicine }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:hospital_id, :name, :category, :description, :restricted, :quantity)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<div id="new_medicine_form">
  <%= form_for @medicine, remote: true, :display => :inline  do |f| %>
      <%= f.submit "Confirm", class: 'btn btn-success' %>
      <%= f.text_field :hospital_id, :placeholder => "Hospital ID" %>
      <%= f.text_field :name, placeholder: "Name" %>
      <%= f.text_field :category, :value => "Category", hidden: true %>
      <%= f.text_area :description, :value => "Description", hidden: true %>
      <%= f.label "Restricted?" %>
      <%= f.check_box :restricted %>
      <%= f.number_field :quantity, placeholder: "Quantity" %>
  <% end %>
</div>

app/views/medicines/_medicine.html.erb
<tr>
  <td><%= link_to "Edit", edit_medicine_path(@medicine), :class => 'btn btn-default' %></td>
  <td><%= @medicine.name %></td>
  <td><%= @medicine.restricted %></td>
  <td><%= @medicine.quantity %></td>
  <td><span class="glyphicon glyphicon-star"></span> </td>
  <td>        
       <%= link_to "Delete", medicine, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
    
  </td>
</tr>

app/views/medicines/create.js.erb
$('#new_medicine_form').remove();
$('#new_medicine_link').show();
// calls a partial called _medicine with a variable called @medicine
$('#medicines').append('<%= j render(@medicine) %>');

app/views/medicines/edit.html.erb
<h1>Editing medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<h1>Listing medicines</h1>

<table>
  <thead>
    <tr>
      <th>Hospital</th>
      <th>Name</th>
      <th>Category</th>
      <th>Description</th>
      <th>Restricted</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.hospital_id %></td>
        <td><%= medicine.name %></td>
        <td><%= medicine.category %></td>
        <td><%= medicine.description %></td>
        <td><%= medicine.restricted %></td>
        <td><%= medicine.quantity %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicine', new_medicine_path %>

app/views/medicines/new.html.erb
<h1>New medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/new.js.erb
$('#new_medicine_link').hide();
$('#meds').after('<%= j render("form") %>');

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hospital:</strong>
  <%= @medicine.hospital_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @medicine.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @medicine.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medicine.description %>
</p>

<p>
  <strong>Restricted:</strong>
  <%= @medicine.restricted %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @medicine.quantity %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>