config/routes.rb
MHacksPillDeliveryQuad::Application.routes.draw do
  resources :requested_medicines

  resources :requests

  resources :histories

  resources :copters

  resources :destinations

  resources :medicines

  resources :users

  resources :hospitals

  root :to => 'hospitals#index'

  match '/process_sms' => 'receive_messages#process_sms', via: [:post]
  post '/send_sms' => 'receive_messages#butts', as: 'send_sms'
  post '/send_group_sms' => 'receive_messages#groupMessage'

  

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :copter
  belongs_to :hospital
  belongs_to :location
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render action: 'show', status: :created, location: @history }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:copter_id, :hospital_id, :destination_id, :time_left, :time_delivered, :time_returned)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<div id="new_history_form">
  <%= form_for @history, remote: true, :display => :inline do |f| %>
    <%= f.submit "Confirm", class: 'btn btn-success' %>
    <%= f.text_field :copter_id, placeholder: "Copter ID" %>
    <%= f.text_field :hospital_id, placeholder: "Hospital ID" %>
    <%= f.text_field :destination_id, placeholder: "Destination ID" %>
    <%= f.text_field :time_left, placeholder: "Time Left" %>
    <%= f.text_field :time_delivered, placeholder: "Time Delivered" %>
    <%= f.text_field :time_returned, placeholder: "Time Returned" %>
  <% end %>
</div>

app/views/histories/_history.html.erb
<tr>
  <td><%= link_to "Edit", edit_history_path(@history), :class => 'btn btn-default' %></td>
  <td><%= @history.copter_id %></td>
  <td><%= @history.hospital_id %></td>
  <td><%= @history.destination_id %></td>
  <td><%= @history.time_left %></td>
  <td><%= @history.time_delivered %></td>
  <td><%= @history.time_returned %></td>
  <td>
    <%= link_to "Delete", history, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
  </td>
</tr>

app/views/histories/create.js.erb
$('#new_history_form').remove();
$('#new_history_link').show();
// calls a partial called _history with a variable called @history
$('#histories').append('<%= j render(@history) %>');

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1>Listing histories</h1>

<table>
  <thead>
    <tr>
      <th>Copter</th>
      <th>Hospital</th>
      <th>Destination</th>
      <th>Time left</th>
      <th>Time delivered</th>
      <th>Time returned</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.copter_id %></td>
        <td><%= history.hospital_id %></td>
        <td><%= history.destination_id %></td>
        <td><%= history.time_left %></td>
        <td><%= history.time_delivered %></td>
        <td><%= history.time_returned %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/new.js.erb
$('#new_history_link').hide();
$('#history').after('<%= j render("form") %>');

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Copter:</strong>
  <%= @history.copter_id %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @history.hospital_id %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @history.destination_id %>
</p>

<p>
  <strong>Time left:</strong>
  <%= @history.time_left %>
</p>

<p>
  <strong>Time delivered:</strong>
  <%= @history.time_delivered %>
</p>

<p>
  <strong>Time returned:</strong>
  <%= @history.time_returned %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>