config/routes.rb
MHacksPillDeliveryQuad::Application.routes.draw do
  resources :requested_medicines

  resources :requests

  resources :histories

  resources :copters

  resources :destinations

  resources :medicines

  resources :users

  resources :hospitals

  root :to => 'hospitals#index'

  match '/process_sms' => 'receive_messages#process_sms', via: [:post]
  post '/send_sms' => 'receive_messages#butts', as: 'send_sms'
  post '/send_group_sms' => 'receive_messages#groupMessage'

  

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	has_many :users
	has_many :copters
	has_many :destinations
	has_many :requests
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
    set_hospital
    @user = User.new
    @admins = User.where("hospital_id = ? and priveledge = ?", @hospital.id, 3)
    @users = User.where("hospital_id = ? and priveledge = ?", @hospital.id, 2)
    @restricted_users = User.where("hospital_id = ? and priveledge = ?", @hospital.id, 1)

    @medicines = Medicine.where("hospital_id = ?", @hospital.id)
    @histories = History.where("hospital_id = ?", @hospital.id)
    @destinations = Destination.where("hospital_id = ?", @hospital.id)
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hospital }
      else
        format.html { render action: 'new' }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :latitude, :longitude)
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% @hospital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<div class="row" style="margin-top:60px; margin-left:14%">
    <p id="notice"><%= notice %></p>

<h1>Listing hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.latitude %></td>
        <td><%= hospital.longitude %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>
</div>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<div class="container">
    <div class="row" style="margin-top:60px">
        <p id="notice"><%= notice %></p>

        <div class="col-xs-8">
            <div class="row">
                <div id="content">
                    <div id="map-canvas" style="height:400px; width:100%;"></div>
                    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                        <li class="active"><a href="#history" data-toggle="tab">History</a></li>
                        <li><a href="#meds" data-toggle="tab">Meds</a></li>
                        <li><a href="#dest" data-toggle="tab">Destination</a></li>
                    </ul>
                    <div id="my-tab-content" class="tab-content">
                        <div class="tab-pane active" id="history">
                            <table class="table table-striped", id="histories">
                <tr>
                  <th style="width: 5%"></th>
                  <th style="width: 15%">ID</th>
                  <th style="width: 15%">Hospital</th>
                  <th style="width: 15%">Destination</th>
                  <th style="width: 15%">Time Left</th>
                  <th style="width: 15%">Time Delivered</th>
                  <th style="width: 15%">Time Returned</th>
                  <th style="width: 5%"></th>
                </tr>

                <% @histories.each do |history| %>
                  <tr>
                    <td><%= link_to "Edit", edit_history_path(history), :class => 'btn btn-default' %></td>
                    <td><%= history.copter_id%></td>
                    <td><%= history.hospital_id %></td>
                    <td><%= history.destination_id %></td>
                    <td><%= history.time_left %></td>
                    <td><%= history.time_delivered %></td>
                    <td><%= history.time_returned %></td>
                    <td>
                      <%= link_to "Delete", history, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                    </td>
                  </tr>
                <% end %>
              </table>
              <%= link_to "New History", new_history_path, id: "new_history_link", remote: true, class: 'btn btn-success' %>
            </div>
                <div class="tab-pane" id="meds">
                    <table class="table table-striped", id="medicines">
                        <tr>
                            <th style="width: 7%"></th>
                            <th style="width: 40%">Name</th>
                            <th style="width: 36%">Restricted</th>
                            <th style="width: 10%">Quantity</th>
                            <th style="width: 7%"></th>
                        </tr>

                        <% @medicines.each do |medicine| %>
                            <tr>
                                <td><%= link_to "Edit", edit_medicine_path(medicine), :class => 'btn btn-default' %></td>
                                <td><%= medicine.name %></td>
                                <td><%= medicine.restricted %></td>
                                <td><%= medicine.quantity %></td>
                                <td>
                                    <%= link_to "Delete", medicine, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                                </td>
                            </tr>
                        <% end %>
                    </table>
                    <%= link_to "New Medicine", new_medicine_path, id: "new_medicine_link", remote: true, class: 'btn btn-success' %>
                </div>
            <div class="tab-pane" id="dest">
              <table class="table table-striped", id="destinations">
                <tr>
                  <th style="width: 5%"></th>
                  <th style="width: 15%">ID</th>
                  <th style="width: 15%">Name</th>
                  <th style="width: 30%">Description</th>
                  <th style="width: 15%">Latitude</th>
                  <th style="width: 15%">Longitude</th>
                  <th style="width: 5%"></th>
                </tr>

                <% @destinations.each do |destination| %>
                  <tr>
                    <td><%= link_to "Edit", edit_destination_path(destination), :class => 'btn btn-default' %></td>
                    <td><%= destination.hospital_id %></td>
                    <td><%= destination.name %></td>
                    <td><%= destination.description %></td>
                    <td><%= destination.latitude %></td>
                    <td><%= destination.longitude %></td>
                    <td>
                      <%= link_to "Delete", destination, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                    </td>
                  </tr>
                <% end %>
              </table>
              <%= link_to "New Destination", new_destination_path, id: "new_destination_link", remote: true, class: 'btn btn-success' %>
            </div>
                    </div>
                </div>

                <script type="text/javascript">
                    $(function() {
                        $('#tabs').tab();
                    });
                </script>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="row" style="padding:0 10px; padding-bottom: 10px">
              <%= link_to "New User", new_user_path, id: "new_user_link", remote: true, class: 'btn btn-success' %>
              <div id="new_user_form_space"></div>
            </div>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#admins" data-toggle="tab">Admins</a></li>
                <li><a href="#users" data-toggle="tab">Users</a></li>
                <li><a href="#restricted-users" data-toggle="tab">Restricted Users</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="admins">
                    <table class="table table-striped" id="admins-table">
                        <tr>
                            <th style="width: 10%"></th>
                            <th style = "width: 40%">Name</th>
                            <th style = "width: 40%">Phone number</th>
                            <th style = "width: 10%"></th>
                        </tr>

                        <% @admins.each do |user| %>
                            <tr>
                                <td><%= link_to "Edit", edit_user_path(user), :class => 'btn btn-default' %></td>
                                <td><%= user.name %></td>
                                <td><%= user.phone_number %></td>
                                <td>
                                    <%= link_to "Delete", user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                                </td>
                            </tr>
                        <% end %>
                    </table>
                </div>
                <div class="tab-pane" id="users">
                    <table class="table table-striped" id="users-table">
                        <tr>
              <th style="width: 10%"></th>
              <th style = "width: 40%">Name</th>
              <th style = "width: 40%">Phone number</th>
              <th style = "width: 10%"></th>
                        </tr>

                        <% @users.each do |user| %>
                            <tr>
                <td><%= link_to "Edit", edit_user_path(user), :class => 'btn btn-default' %></td>
                                <td><%= user.name %></td>
                                <td><%= user.phone_number %></td>
                <td>
                  <%= link_to "Delete", user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                </td>
                            </tr>
                        <% end %>
                    </table>
                </div>
                <div class="tab-pane" id="restricted-users">
                    <table class="table table-striped" id="restricted-users-table">
                        <tr>
                            <th style="width: 10"></th>
                            <th style="width: 40">Name</th>
                            <th style="width: 40">Phone number</th>
                            <th style="width: 10"></th>
                        </tr>

                        <% @restricted_users.each do |user| %>
                            <tr>
                                <td><%= link_to "Edit", edit_user_path(user), :class => 'btn btn-default' %></td>
                                <td><%= user.name %></td>
                                <td><%= user.phone_number %></td>
                                <td>
                                    <%= link_to "Delete", user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
                                </td>
                            </tr>
                        <% end %>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>